Repository DEFRA/waste-carriers-acceptance-tests, pull requests merged in 2020-06, with the labels that each got.

#320 Switch Quke branch to main
  Gemfile
  Gemfile.lock
Labels: housekeeping

#321 Update Travis config
  .travis.yml
  Rakefile
Labels: housekeeping

#322 Move config to its own folder for consistency
  .config.yml
  .gitignore
  README.md
  Rakefile
  config/browserstack/chrome63_osx.config.yml
  config/browserstack/chrome63_w7.config.yml
  config/browserstack/chrome64_osx.config.yml
  config/browserstack/edge15_w10.config.yml
  config/browserstack/edge16_w10.config.yml
  config/browserstack/firefox58_osx.config.yml
  config/browserstack/firefox58_w8_1.config.yml
  config/browserstack/firefox59_osx.config.yml
  config/browserstack/firefox59_w10.config.yml
  config/browserstack/galaxy_note_8.config.yml
  config/browserstack/google_pixel.config.yml
  config/browserstack/ie11_w10.config.yml
  config/browserstack/iphone_7.config.yml
  config/browserstack/iphone_x.config.yml
  config/browserstack/safari10_1_osx.config.yml
  config/browserstack/safari11_osx.config.yml
  config/browserstack/safari9_1_osx.config.yml
  config/ci.config.yml
  config/dev.config.yml
  config/loc.config.yml
  config/pre.config.yml
  config/tst.config.yml
Labels: housekeeping

#323 Update comments and args on browserstack config
  config/browserstack/chrome63_osx.config.yml
  config/browserstack/chrome63_w7.config.yml
  config/browserstack/chrome64_osx.config.yml
  config/browserstack/edge15_w10.config.yml
  config/browserstack/edge16_w10.config.yml
  config/browserstack/firefox58_osx.config.yml
  config/browserstack/firefox58_w8_1.config.yml
  config/browserstack/firefox59_osx.config.yml
  config/browserstack/firefox59_w10.config.yml
  config/browserstack/galaxy_note_8.config.yml
  config/browserstack/google_pixel.config.yml
  config/browserstack/ie11_w10.config.yml
  config/browserstack/iphone_7.config.yml
  config/browserstack/iphone_x.config.yml
  config/browserstack/safari10_1_osx.config.yml
  config/browserstack/safari11_osx.config.yml
  config/browserstack/safari9_1_osx.config.yml
Labels: housekeeping

#326 Update seed data request to handle https sites
  features/seeds/seed_data.rb
Labels: bug

#328 Update documentation for Seed usage
  features/seeds/README.md
Labels: enhancement

#330 Unblock and enable renew expired registrations
  config/loc.config.yml
  features/fo_new/renewals/renew_from_email.feature
  features/seeds/README.md
  features/seeds/fixtures/limitedCompany_expired_registration.json
  features/step_definitions/front_office/renewal_steps.rb
  features/support/renewal_helpers.rb
Labels: enhancement
